### ISSUE TITLE
Installation Instructions Not Visible in Night Mode in readthedocs

### ISSUE THREAD

**Issue by sebbyjp** [mbodiai/embodied-agents#30]
<img width="1375" alt="image" src="https://github.com/MbodiAI/mbodied-agents/assets/22511797/f2d6ec98-e32e-4aac-b7aa-990641233867">

**Comment by charusingh96** [comment]
This seems to have been fixed.

![Screenshot from 2024-07-13 22-22-34](https://github.com/user-attachments/assets/569131cb-209e-4b0d-bbd8-24e6af7bc7eb)

One more issue observed is i have to individually set dark mode for each page seperately.
